In [1]:
import numpy as np

In [2]:
hw = np.arange(0, 21, 1)
hw

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
hw2 = hw[0::2]
hw2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
hw3 = hw[3::3]
hw3

array([ 3,  6,  9, 12, 15, 18])